openapi: 3.0.0
info:
  version: 1.0.0
  title: Postchat API
servers:
  - url: "/api/v1"
paths:
  /rooms/{id}:
    get:
      summary: "Returns messsages and details for the given room"
      operationId: getRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Details about a room by ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
        "404":
          description: "Room not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /rooms/{id}/message:
    post:
      summary: "Adds a messsage to the given room"
      operationId: createMessage
      tags:
        - room
      parameters:
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                username:
                  type: string
              required:
                - text
                - username
      responses:
        "200":
          description: "Details about created message"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /rooms:
    post:
      summary: "Adds a room"
      operationId: createMessage
      tags:
        - room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        "200":
          description: "Details about created room"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Room:
      type: object
      required:
        - _id
        - title
      properties:
        _id:
          type: string
        title:
          type: string
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
    Message:
      type: object
      required:
        - _id
        - text
        - username
      properties:
        _id:
          type: string
        text:
          type: string
        username:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        errors:
          type: array
          items: {} # any type

